# Generated by Django 2.1.1 on 2019-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='surname',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
