# Generated by Django 2.2.5 on 2019-09-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='operators.Service'),
        ),
    ]
