# Generated by Django 2.2.5 on 2019-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_auto_20190922_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='operators_id',
            new_name='operator',
        ),
    ]
