# Generated by Django 2.2.5 on 2019-09-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0004_auto_20190922_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turn', to='operators.Operator'),
        ),
    ]
